"""Make current_value nullable and add reminder to KPI

Revision ID: 11e7e10b64ac
Revises: eb80bf191f02
Create Date: 2025-05-13 18:34:41.055398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e7e10b64ac'
down_revision = 'eb80bf191f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder', sa.String(length=20), nullable=True))
        batch_op.alter_column('current_value',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi', schema=None) as batch_op:
        batch_op.alter_column('current_value',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('reminder')

    # ### end Alembic commands ###
