"""Remove assigned_to_id from KPI

Revision ID: b46dbced3e2d
Revises: 11e7e10b64ac
Create Date: 2025-05-13 18:36:49.684697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'b46dbced3e2d'
down_revision = '11e7e10b64ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Get the foreign key constraint name
    fks = inspector.get_foreign_keys('kpi')
    fk_name = None
    for fk in fks:
        if 'assigned_to_id' in fk['constrained_columns']:
            fk_name = fk['name']
            break
    
    with op.batch_alter_table('kpi', schema=None) as batch_op:
        if fk_name:
            batch_op.drop_constraint(fk_name, type_='foreignkey')
        batch_op.drop_column('assigned_to_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_kpi_assigned_to_id', 'user', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###
