"""Add current_value and other new KPI fields

Revision ID: d5740585ad93
Revises: 
Create Date: 2025-05-13 16:29:18.108491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5740585ad93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_value', sa.Float(), nullable=False, server_default='0'))
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('benchmark_value',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('benchmark_type')
        batch_op.drop_column('actual_value')
        batch_op.drop_column('target_value')
    # Remove the server_default after the column is created
    with op.batch_alter_table('kpi', schema=None) as batch_op:
        batch_op.alter_column('current_value', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_value', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('actual_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('benchmark_value',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('current_value')

    # ### end Alembic commands ###
